const api = require('../../../utils/request')
const { getUser, requireLogin } = require('../../../utils/auth')
const { refreshUnreadBadge } = require('../../../utils/unread')
const { normalizeImageUrl } = require('../../../utils/image')
const { formatDateTime, money } = require('../../../utils/format')

Page({
  data: { conversationId: '', receiverId: '', productId: '', orderId: '', product: {}, messages: [], content: '', currentUserId: '', showEmoji: false, showPlus: false, voiceMode: false, recording: false, supportMode: false, emojis: ['😀', '😄', '😂', '👍', '🙏', '🎉'], scrollIntoView: '' },
  onLoad(options) { requireLogin(); const user = getUser() || {}; this.setData({ conversationId: options.conversation_id || '', receiverId: options.receiver_id || '', productId: options.product_id || '', orderId: options.order_id || '', currentUserId: user.id || '', supportMode: options.support === '1', product: { title: options.product_title ? decodeURIComponent(options.product_title) : '', price: options.product_price ? money(options.product_price) : '', cover_image: normalizeImageUrl(options.product_cover ? decodeURIComponent(options.product_cover) : '', 'product') } }); if (options.support === '1') wx.setNavigationBarTitle({ title: '平台客服' }); this.initRecorder(); this.loadMessages() },
  initRecorder() { if (!wx.getRecorderManager) return; this.recorder = wx.getRecorderManager(); this.recorder.onStop((res) => { this.setData({ recording: false }); api.uploadFile({ url: '/files/upload', filePath: res.tempFilePath, formData: { usage: 'chat' }, loading: true }).then((data) => this.sendMessage({ message_type: 'voice', image_url: data.url, content: '[语音]' })) }) },
  onInput(event) { this.setData({ content: event.detail.value }) },
  loadMessages() { if (!this.data.conversationId) return; api.get(`/messages/${this.data.conversationId}`).then((data) => { const context = data.context || {}; const contextProduct = context.product || {}; let previous = 0; const messages = (data.items || []).map((item) => { const stamp = new Date(item.created_at).getTime(); const result = Object.assign({}, item, { mine: item.is_mine || item.sender_id === this.data.currentUserId, show_time: !previous || stamp - previous > 5 * 60 * 1000, time_text: formatDateTime(item.created_at), content: item.content || '' }); previous = stamp; return result }); const nextData = { messages, scrollIntoView: messages.length ? `msg-${messages[messages.length - 1].id}` : '' }; if (context.order_id && !this.data.orderId) nextData.orderId = context.order_id; if (contextProduct.title && !this.data.product.title) { nextData.productId = contextProduct.id || this.data.productId; nextData.product = { title: contextProduct.title || '', price: contextProduct.price ? money(contextProduct.price) : '', cover_image: normalizeImageUrl(contextProduct.cover_image || '', 'product') } } this.setData(nextData); refreshUnreadBadge() }) },
  sendText() { const content = this.data.content.trim(); if (content) this.sendMessage({ message_type: 'text', content }) },
  toggleVoice() { this.setData({ voiceMode: !this.data.voiceMode, showEmoji: false, showPlus: false }) },
  toggleEmoji() { this.setData({ showEmoji: !this.data.showEmoji, showPlus: false }) },
  togglePlus() { this.setData({ showPlus: !this.data.showPlus, showEmoji: false }) },
  addEmoji(event) { this.setData({ content: this.data.content + event.currentTarget.dataset.value }) },
  startVoice() { if (!this.recorder) return; this.setData({ recording: true }); this.recorder.start({ duration: 60000, format: 'mp3' }) },
  stopVoice() { if (this.recorder && this.data.recording) this.recorder.stop() },
  chooseMedia(event) { const sourceType = event.currentTarget.dataset.source || 'album'; wx.chooseMedia({ count: 1, mediaType: ['image', 'video'], sizeType: ['compressed'], sourceType: [sourceType], success: (res) => { const file = res.tempFiles[0]; const type = res.type === 'video' ? 'video' : 'image'; api.uploadFile({ url: '/files/upload', filePath: file.tempFilePath, formData: { usage: 'chat' }, loading: true }).then((data) => this.sendMessage({ message_type: type, image_url: data.url, content: type === 'video' ? '[视频]' : '[图片]' })) } }) },
  viewReview(event) { wx.navigateTo({ url: `/pages/review/detail/index?id=${event.currentTarget.dataset.id}` }) },
  previewImage(event) { wx.previewImage({ urls: [event.currentTarget.dataset.url] }) },
  viewProduct() { if (this.data.orderId) return wx.navigateTo({ url: `/pages/order/detail/index?id=${this.data.orderId}` }); if (this.data.productId) wx.navigateTo({ url: `/pages/product/detail/index?id=${this.data.productId}` }) },
  viewUser(event) { const userId = event.currentTarget.dataset.id; if (userId) wx.navigateTo({ url: `/pages/profile/home/index?id=${userId}` }) },
  sendMessage(extra) { if (!this.data.receiverId) return wx.showToast({ title: '缺少收信人', icon: 'none' }); api.post('/messages', Object.assign({ receiver_id: this.data.receiverId, product_id: this.data.productId, order_id: this.data.orderId }, extra), { loading: true }).then((message) => { this.setData({ content: '', conversationId: this.data.conversationId || message.conversation_id, showEmoji: false, showPlus: false }); this.loadMessages() }) }
})
