const api = require('../../../utils/request')
const { requireLogin } = require('../../../utils/auth')
const { refreshUnreadBadge } = require('../../../utils/unread')
const { refundStatus, formatDateTime, money, safeText } = require('../../../utils/format')

const STATUS_TIP = { pending: '请在规定时间内处理，超时将自动同意退款', refunding: '退款处理中', refunded: '退款已完成', rejected: '退款已拒绝', closed: '售后已关闭' }

Page({
  data: { id: '', refund: null, loading: false },
  onLoad(options) { this.setData({ id: options.id || '' }) },
  onShow() { if (!requireLogin()) return; this.loadDetail() },
  onPullDownRefresh() { this.loadDetail(); wx.stopPullDownRefresh() },
  loadDetail() { if (!this.data.id) return wx.showToast({ title: '售后单不存在', icon: 'none' }); this.setData({ loading: true }); api.get(`/refunds/${this.data.id}`, {}, { loading: true, loadingText: '加载售后' }).then((data) => { const group = data.status_group || data.status; const product = data.product || {}; const contact = data.contact_user || {}; const refund = Object.assign({}, data, { status_text: refundStatus(data.status, data.status_group), status_tip: STATUS_TIP[group] || '', created_text: formatDateTime(data.created_at), handled_text: formatDateTime(data.seller_handled_at), amount_text: money(data.display_amount || data.request_amount || data.amount), reason_display: safeText(data.reason_text || data.reason, '未填写'), description_display: safeText(data.description, '未填写'), product: Object.assign({}, product, { title: safeText(product.title, '售后商品'), price_text: money(product.price || data.display_amount || data.amount), quantity: Number(product.quantity || 1) }), contact_user: Object.assign({}, contact, { nickname: safeText(contact.nickname, '校内同学'), phone_masked: safeText(contact.phone_masked, '未填写') }), contact_title: data.current_role === 'buyer' ? '卖家信息' : '买家信息', contact_label: data.current_role === 'buyer' ? '联系卖家' : '联系买家' }); this.setData({ refund }); refreshUnreadBadge() }).catch(() => wx.showToast({ title: '售后详情加载失败，请重试', icon: 'none' })).finally(() => this.setData({ loading: false })) },
  copyText(event) { const value = event.currentTarget.dataset.value; if (value) wx.setClipboardData({ data: value }) },
  previewEvidence(event) { const current = event.currentTarget.dataset.url; const urls = (this.data.refund && this.data.refund.evidence_images) || []; if (current && urls.length) wx.previewImage({ current, urls }) },
  contactCounterparty() { const refund = this.data.refund; const user = refund && refund.contact_user; if (!refund || !user || !user.id) return wx.showToast({ title: '联系人信息不存在', icon: 'none' }); const product = refund.product || {}; wx.navigateTo({ url: `/pages/message/chat/index?conversation_id=${refund.conversation_id || ''}&receiver_id=${user.id}&product_id=${product.id || ''}&order_id=${refund.order_id || (refund.order && refund.order.id) || ''}&product_title=${encodeURIComponent(product.title || '')}&product_price=${product.price || ''}&product_cover=${encodeURIComponent(product.cover_image || '')}` }) },
  agreeRefund() { wx.showModal({ title: '同意退款', content: '确认同意该售后申请并处理退款吗？', confirmText: '同意退款', success: (res) => { if (!res.confirm) return; api.post(`/refunds/${this.data.id}/seller-handle`, { action: 'agree', reason: '卖家同意退款' }, { loading: true, loadingText: '处理中' }).then(() => { wx.showToast({ title: '已同意退款', icon: 'success' }); this.loadDetail() }) } }) },
  refuseRefund() { wx.showModal({ title: '拒绝退款', content: '请填写拒绝原因，原因会发送给买家。', editable: true, placeholderText: '请输入拒绝原因', confirmText: '确认拒绝', success: (res) => { if (!res.confirm) return; const reason = (res.content || '').trim(); if (!reason) return wx.showToast({ title: '请填写拒绝原因', icon: 'none' }); api.post(`/refunds/${this.data.id}/seller-handle`, { action: 'refuse', reason }, { loading: true, loadingText: '处理中' }).then(() => { wx.showToast({ title: '已拒绝退款', icon: 'success' }); this.loadDetail() }) } }) }
})
